name: pasiya_md_mobile
description: PASIYA-MD mobile app (offline-first)
version: 0.1.0
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  hive: ^2.2.3
  path_provider: ^2.1.0
